# Generated by Django 4.1.6 on 2023-03-01 01:37

import api_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imageurl', models.ImageField(upload_to=api_portfolio.models.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Abouts',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('imageurl', models.ImageField(upload_to=api_portfolio.models.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Brands',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bgColor', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(upload_to=api_portfolio.models.upload_to, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('imageurl', models.ImageField(upload_to=api_portfolio.models.upload_to, verbose_name='Image')),
                ('feedback', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('projectLink', models.CharField(max_length=150)),
                ('codeLink', models.CharField(max_length=150)),
                ('imageurl', models.ImageField(upload_to=api_portfolio.models.upload_to, verbose_name='Image')),
                ('tag', models.ManyToManyField(blank=True, related_name='works', to='api_portfolio.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=50)),
                ('work', models.ManyToManyField(blank=True, related_name='experiences', to='api_portfolio.workexperience')),
            ],
        ),
    ]
